version: '3.1'

networks:
  app-tier:
    driver: bridge

services:
  mysql:
    image: 'bitnami/mysql:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - app-tier
    ports:
      - "3306:3306"
  myapp:
    image: 'bitnami/mysql:latest'
    networks:
      - app-tier
